### ISSUE TITLE
响应不到activity的onResume方法

### ISSUE THREAD

**Issue by wudicsy** [HiJesse/Android-AOP#1]
博主你好，如果我的activity里没有实现onResume方法，就拦截不到了，这样要怎么解决呢

**Comment by HiJesse** [comment]
@wudicsy 这个在博客的AOP Weaving部分有解释. 反向代码能看出sample中对onResume的切片是在现有方法前插入一些代码, 代码中没有可匹配Pointcut的方法就不会做AOP. 通常组件的生命周期方法在基类都会复写的. 如果想要更加灵活的实现AOP也可以考虑使用ASM.

**Comment by wudicsy** [comment]
谢谢博主，如果我的activity是在别的module，应该怎么拦截呢@HiJesse

**Comment by HiJesse** [comment]
@wudicsy apply plugin: 'android-aop'所在的module里面依赖想要插桩的module就行了

**Comment by wudicsy** [comment]
@HiJesse   谢谢啦，假如我的app有多个module继承，每个module中都有我想要拦截的方法，我需要在每个module中都重写ActivityAOP这个类吗，我试了几次，如果不都重写的话，好像拦截不到，请问这是为什么呢

**Comment by HiJesse** [comment]
@wudicsy 不客气, 我感觉你说这种情况是因为编译顺序问题. 假设A module依赖B module, 你在A module里写了Aspect类, 想要在B module生效对吧. 其实在编译的时候是先编译B再编译A的, 而Aspect在A里面, 编译B的时候B是没有Aspect类的, 所以B编译完之后就没有在目标类的目标方法做AOP. 这种情况可以尝试在一个base module里写Aspect类.
